### ISSUE TITLE
Coursework feedback

### ISSUE THREAD

**Issue by NYBACHOK** [vadimpk/rust-english-parser#1]
Student: Поліщук Вадим

Не вистачає для прохідного:
:heavy_check_mark:  ! Project Name: 
:heavy_check_mark: ! Grammar Rules: 
:heavy_check_mark: ! CLI:
:heavy_check_mark: ! Brief Description:
:heavy_check_mark: ! Unit Tests:
:heavy_check_mark: ! Core Files:

Не вистачає для мааксимального:
✔️ File System:
:heavy_check_mark: Test Coverage: допустимо
:heavy_check_mark: Error Handling: 
:heavy_check_mark: cargo fmt:
✔️ cargo clippy:
:heavy_check_mark:  makefile:
✔️  Completeness:  
:heavy_check_mark: Including a diagram or grammar in the Readme.md:
:heavy_check_mark: Documentation:
✔️  Publishing: 

:heavy_check_mark: Курсова може бути зарахована
Бал: 25/25

**Comment by vadimpk** [comment]
> ❌ File System: умова записана [як](https://github.com/rust-lang-ua/kma_rust_course/blob/dd6c38cab9d3171d12a05d262a768309edb364f2/6_parser_final/evaluation.md) aRead input from file *and write output to a file SPECIFIED by user.* . Заміни bool на Option<PathBuf>

Сорі, в мене немає доступу до посилання, тому я орієнтувався на умову на [дістеду](https://distedu.ukma.edu.ua/mod/assign/view.php?id=128777), а там не було про таке написано, тому я імпровізував)

**Comment by vadimpk** [comment]
Доробив і запушив нову версію: https://crates.io/crates/english-language-parser

**Comment by vadimpk** [comment]
@NYBACHOK Все влаштовує
